theme: osuny
_merge: deep
params:
  debug:
    productionUrl: https://fondation-jacques-rougerie.com
  plausible: fondation-jacques-rougerie.com
  logo:
    header: "/assets/images/logo-icon.svg"
    footer: "/assets/images/logo-white.svg"
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
